export {
  SYSTEM_ACCOUNT_TOKEN,
  SYSTEM_ACCOUNT_API_ACCOUNT,
  SYSTEM_ACCOUNT_API_ACCOUNT_NEWACCOUNT,
  SYSTEM_ACCOUNT_API_ACCOUNT_LOGIN,
  SYSTEM_ACCOUNT_API_ACCOUNT_ACCOUNTNAMEEXISTED,
  SYSTEM_ACCOUNT_API_ACCOUNT_BASICINFORMATION,
  SYSTEM_ACCOUNT_API_BOSS,
  SYSTEM_ACCOUNT_API_BOSS_QUERYACCOUNTS,
}

const SYSTEM_ACCOUNT_TOKEN = 'SYSTEM_ACCOUNT_TOKEN'

const SYSTEM_ACCOUNT_API_ACCOUNT = 'Account'
const SYSTEM_ACCOUNT_API_ACCOUNT_NEWACCOUNT = '/create'
const SYSTEM_ACCOUNT_API_ACCOUNT_LOGIN = '/login'
const SYSTEM_ACCOUNT_API_ACCOUNT_ACCOUNTNAMEEXISTED = '/LoginNameExists'
const SYSTEM_ACCOUNT_API_ACCOUNT_BASICINFORMATION = '/BasicInformation'

const SYSTEM_ACCOUNT_API_BOSS = 'Boss'
const SYSTEM_ACCOUNT_API_BOSS_QUERYACCOUNTS = '/queryAccounts'
